In [3]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.6.0+cu124


In [4]:
## Intro to tensors

# scalar
scalar = torch.tensor(7)
scalar

# use torch.Tensor() to create PyTorch tensors

tensor(7)

In [5]:
torch.rand(3, 3)

tensor([[0.2121, 0.0056, 0.7158],
        [0.8084, 0.2235, 0.1390],
        [0.7162, 0.8115, 0.5103]])

In [6]:
random_image_size_tensor = torch.rand(size=(3, 10,10))
random_image_size_tensor.shape, random_image_size_tensor.ndim
random_image_size_tensor

tensor([[[0.2966, 0.2588, 0.7343, 0.1360, 0.0085, 0.4469, 0.2900, 0.8036,
          0.2326, 0.1159],
         [0.3793, 0.1634, 0.4294, 0.9064, 0.5894, 0.1815, 0.4130, 0.5836,
          0.4060, 0.7830],
         [0.7661, 0.4717, 0.9354, 0.8308, 0.9331, 0.6757, 0.6451, 0.7213,
          0.0527, 0.0134],
         [0.3538, 0.9002, 0.4694, 0.9917, 0.2222, 0.5706, 0.4038, 0.5567,
          0.1230, 0.9364],
         [0.9055, 0.1581, 0.2559, 0.4012, 0.3100, 0.6573, 0.1668, 0.4560,
          0.1966, 0.3496],
         [0.6595, 0.1085, 0.3423, 0.8201, 0.1987, 0.2422, 0.2102, 0.7856,
          0.3783, 0.9284],
         [0.6262, 0.4387, 0.4073, 0.1279, 0.7879, 0.1810, 0.6586, 0.2590,
          0.1404, 0.1274],
         [0.3774, 0.9476, 0.7414, 0.9560, 0.9779, 0.1136, 0.8549, 0.4567,
          0.3453, 0.7530],
         [0.0346, 0.3015, 0.7048, 0.4440, 0.8883, 0.3563, 0.8291, 0.1002,
          0.7664, 0.7987],
         [0.7306, 0.2938, 0.4469, 0.7005, 0.7566, 0.2305, 0.8901, 0.8845,
          0.0446,

In [7]:
# create tensor of all 0s
zeros = torch.zeros(size=(3,4))
ones = torch.ones(size=(3,4))
print(zeros)
print(ones)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


In [8]:
random_image_size_tensor.dtype

torch.float32

In [9]:
# creating a tensor with a range
woow = torch.arange(1,11)

torch.arange(start = 0, end = 38, step = 2)

tensor([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
        36])

In [10]:
 ten_zeros = torch.zeros_like(input = woow)
 ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

#Tensor datatypes

In [11]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0], dtype = torch.float32, device=None, requires_grad=False)
float_32_tensor

tensor([3., 6., 9.])

In [14]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [19]:
mult = float_16_tensor * float_32_tensor
print(mult.dtype)
# changes it to a float_32

torch.float32
